# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LCL.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 689)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(-90, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.target_screenshot_button = QtWidgets.QPushButton(self.centralwidget)
        self.target_screenshot_button.setGeometry(QtCore.QRect(3, 3, 71, 31))
        self.target_screenshot_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.target_screenshot_button.setObjectName("target_screenshot_button")
        self.non_target_screenshot_button = QtWidgets.QPushButton(self.centralwidget)
        self.non_target_screenshot_button.setGeometry(QtCore.QRect(73, 3, 71, 31))
        self.non_target_screenshot_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.non_target_screenshot_button.setObjectName("non_target_screenshot_button")
        self.misc_screenshot_button = QtWidgets.QPushButton(self.centralwidget)
        self.misc_screenshot_button.setGeometry(QtCore.QRect(3, 33, 71, 31))
        self.misc_screenshot_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.misc_screenshot_button.setObjectName("misc_screenshot_button")
        self.comment_box = QtWidgets.QTextEdit(self.centralwidget)
        self.comment_box.setGeometry(QtCore.QRect(4, 83, 131, 41))
        self.comment_box.setObjectName("comment_box")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(7, 292, 131, 191))
        self.groupBox.setObjectName("groupBox")
        self.down_button = QtWidgets.QPushButton(self.groupBox)
        self.down_button.setGeometry(QtCore.QRect(38, 60, 51, 23))
        self.down_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.down_button.setObjectName("down_button")
        self.right_button = QtWidgets.QPushButton(self.groupBox)
        self.right_button.setGeometry(QtCore.QRect(59, 40, 51, 23))
        self.right_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.right_button.setObjectName("right_button")
        self.up_button = QtWidgets.QPushButton(self.groupBox)
        self.up_button.setGeometry(QtCore.QRect(37, 20, 51, 23))
        self.up_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.up_button.setObjectName("up_button")
        self.left_button = QtWidgets.QPushButton(self.groupBox)
        self.left_button.setGeometry(QtCore.QRect(13, 40, 51, 23))
        self.left_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.left_button.setObjectName("left_button")
        self.home_stage_button = QtWidgets.QPushButton(self.groupBox)
        self.home_stage_button.setGeometry(QtCore.QRect(25, 84, 75, 23))
        self.home_stage_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.home_stage_button.setObjectName("home_stage_button")
        self.get_position_button = QtWidgets.QPushButton(self.groupBox)
        self.get_position_button.setGeometry(QtCore.QRect(25, 104, 75, 23))
        self.get_position_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.get_position_button.setObjectName("get_position_button")
        self.step_size_doublespin_box = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.step_size_doublespin_box.setGeometry(QtCore.QRect(29, 150, 62, 22))
        self.step_size_doublespin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.step_size_doublespin_box.setDecimals(0)
        self.step_size_doublespin_box.setMinimum(50.0)
        self.step_size_doublespin_box.setMaximum(10000.0)
        self.step_size_doublespin_box.setSingleStep(50.0)
        self.step_size_doublespin_box.setProperty("value", 1000.0)
        self.step_size_doublespin_box.setObjectName("step_size_doublespin_box")
        self.step_size_label = QtWidgets.QLabel(self.groupBox)
        self.step_size_label.setGeometry(QtCore.QRect(29, 130, 47, 13))
        self.step_size_label.setObjectName("step_size_label")
        self.comment_box_label = QtWidgets.QLabel(self.centralwidget)
        self.comment_box_label.setGeometry(QtCore.QRect(6, 63, 71, 16))
        self.comment_box_label.setObjectName("comment_box_label")
        self.user_comment_button = QtWidgets.QPushButton(self.centralwidget)
        self.user_comment_button.setGeometry(QtCore.QRect(3, 123, 131, 23))
        self.user_comment_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.user_comment_button.setObjectName("user_comment_button")
        self.magnification_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.magnification_combobox.setGeometry(QtCore.QRect(10, 170, 61, 22))
        self.magnification_combobox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.magnification_combobox.setEditable(True)
        self.magnification_combobox.setCurrentText("")
        self.magnification_combobox.setObjectName("magnification_combobox")
        self.magnification_label = QtWidgets.QLabel(self.centralwidget)
        self.magnification_label.setGeometry(QtCore.QRect(9, 150, 71, 16))
        self.magnification_label.setObjectName("magnification_label")
        self.calibration_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.calibration_groupbox.setGeometry(QtCore.QRect(7, 196, 131, 91))
        self.calibration_groupbox.setObjectName("calibration_groupbox")
        self.upper_left_calibration_button = QtWidgets.QPushButton(self.calibration_groupbox)
        self.upper_left_calibration_button.setGeometry(QtCore.QRect(27, 20, 70, 23))
        self.upper_left_calibration_button.setObjectName("upper_left_calibration_button")
        self.bottom_left_calibration_button = QtWidgets.QPushButton(self.calibration_groupbox)
        self.bottom_left_calibration_button.setGeometry(QtCore.QRect(27, 40, 70, 23))
        self.bottom_left_calibration_button.setObjectName("bottom_left_calibration_button")
        self.bottom_right_calibration_button = QtWidgets.QPushButton(self.calibration_groupbox)
        self.bottom_right_calibration_button.setGeometry(QtCore.QRect(27, 60, 70, 23))
        self.bottom_right_calibration_button.setObjectName("bottom_right_calibration_button")
        self.load_image_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.load_image_pushbutton.setGeometry(QtCore.QRect(73, 169, 71, 23))
        self.load_image_pushbutton.setObjectName("load_image_pushbutton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(145, 3, 851, 681))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.laser_controls_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.laser_controls_groupbox.setGeometry(QtCore.QRect(10, 480, 120, 201))
        self.laser_controls_groupbox.setObjectName("laser_controls_groupbox")
        self.start_flashlamp_pushbutton = QtWidgets.QPushButton(self.laser_controls_groupbox)
        self.start_flashlamp_pushbutton.setGeometry(QtCore.QRect(10, 20, 101, 23))
        self.start_flashlamp_pushbutton.setObjectName("start_flashlamp_pushbutton")
        self.stop_flashlamp_pushbutton = QtWidgets.QPushButton(self.laser_controls_groupbox)
        self.stop_flashlamp_pushbutton.setGeometry(QtCore.QRect(10, 50, 101, 23))
        self.stop_flashlamp_pushbutton.setObjectName("stop_flashlamp_pushbutton")
        self.fire_qswitch_pushbutton = QtWidgets.QPushButton(self.laser_controls_groupbox)
        self.fire_qswitch_pushbutton.setGeometry(QtCore.QRect(10, 80, 101, 23))
        self.fire_qswitch_pushbutton.setObjectName("fire_qswitch_pushbutton")
        self.qswitch_delay_doublespin_box = QtWidgets.QDoubleSpinBox(self.laser_controls_groupbox)
        self.qswitch_delay_doublespin_box.setGeometry(QtCore.QRect(10, 127, 101, 22))
        self.qswitch_delay_doublespin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.qswitch_delay_doublespin_box.setDecimals(0)
        self.qswitch_delay_doublespin_box.setMinimum(50.0)
        self.qswitch_delay_doublespin_box.setMaximum(10000.0)
        self.qswitch_delay_doublespin_box.setSingleStep(5.0)
        self.qswitch_delay_doublespin_box.setProperty("value", 200.0)
        self.qswitch_delay_doublespin_box.setObjectName("qswitch_delay_doublespin_box")
        self.Qswitch_delay_label = QtWidgets.QLabel(self.laser_controls_groupbox)
        self.Qswitch_delay_label.setGeometry(QtCore.QRect(10, 108, 101, 16))
        self.Qswitch_delay_label.setObjectName("Qswitch_delay_label")
        self.attenuator_label = QtWidgets.QLabel(self.laser_controls_groupbox)
        self.attenuator_label.setGeometry(QtCore.QRect(10, 150, 101, 16))
        self.attenuator_label.setObjectName("attenuator_label")
        self.attenuator_doublespin_box = QtWidgets.QDoubleSpinBox(self.laser_controls_groupbox)
        self.attenuator_doublespin_box.setGeometry(QtCore.QRect(10, 170, 101, 22))
        self.attenuator_doublespin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.attenuator_doublespin_box.setDecimals(2)
        self.attenuator_doublespin_box.setMinimum(0.0)
        self.attenuator_doublespin_box.setMaximum(100.0)
        self.attenuator_doublespin_box.setSingleStep(0.1)
        self.attenuator_doublespin_box.setProperty("value", 0.6)
        self.attenuator_doublespin_box.setObjectName("attenuator_doublespin_box")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LCL System"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.target_screenshot_button.setText(_translate("MainWindow", "Target \n"
" Screenshot"))
        self.non_target_screenshot_button.setText(_translate("MainWindow", "Non-Target \n"
" Screenshot"))
        self.misc_screenshot_button.setText(_translate("MainWindow", "Misc. \n"
" Screenshot"))
        self.groupBox.setTitle(_translate("MainWindow", "Stage Controls"))
        self.down_button.setText(_translate("MainWindow", "Down"))
        self.right_button.setText(_translate("MainWindow", "Right"))
        self.up_button.setText(_translate("MainWindow", "Up"))
        self.left_button.setText(_translate("MainWindow", "Left"))
        self.home_stage_button.setText(_translate("MainWindow", "Home Stage"))
        self.get_position_button.setText(_translate("MainWindow", "Get Position"))
        self.step_size_label.setText(_translate("MainWindow", "Step Size"))
        self.comment_box_label.setText(_translate("MainWindow", "Comment box"))
        self.user_comment_button.setText(_translate("MainWindow", "Add comment to log"))
        self.magnification_label.setText(_translate("MainWindow", "Magnification"))
        self.calibration_groupbox.setTitle(_translate("MainWindow", "Substrate Calibration"))
        self.upper_left_calibration_button.setText(_translate("MainWindow", "Upper Left"))
        self.bottom_left_calibration_button.setText(_translate("MainWindow", "Bottom Left"))
        self.bottom_right_calibration_button.setText(_translate("MainWindow", "Bottom Right"))
        self.load_image_pushbutton.setText(_translate("MainWindow", "Load Image"))
        self.laser_controls_groupbox.setTitle(_translate("MainWindow", "Laser Controls"))
        self.start_flashlamp_pushbutton.setText(_translate("MainWindow", "Flash Lamp Auto"))
        self.stop_flashlamp_pushbutton.setText(_translate("MainWindow", "Flash Lamp Off"))
        self.fire_qswitch_pushbutton.setText(_translate("MainWindow", "Fire Q-Switch"))
        self.Qswitch_delay_label.setText(_translate("MainWindow", "Q Switch Delay [us]"))
        self.attenuator_label.setText(_translate("MainWindow", "Attenuator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

