# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LCL.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1505, 733)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(-90, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.misc_screenshot_button = QtWidgets.QPushButton(self.centralwidget)
        self.misc_screenshot_button.setGeometry(QtCore.QRect(10, 0, 131, 31))
        self.misc_screenshot_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.misc_screenshot_button.setObjectName("misc_screenshot_button")
        self.comment_box = QtWidgets.QTextEdit(self.centralwidget)
        self.comment_box.setGeometry(QtCore.QRect(10, 53, 131, 41))
        self.comment_box.setObjectName("comment_box")
        self.comment_box_label = QtWidgets.QLabel(self.centralwidget)
        self.comment_box_label.setGeometry(QtCore.QRect(6, 30, 121, 16))
        self.comment_box_label.setObjectName("comment_box_label")
        self.user_comment_button = QtWidgets.QPushButton(self.centralwidget)
        self.user_comment_button.setGeometry(QtCore.QRect(10, 93, 131, 23))
        self.user_comment_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.user_comment_button.setObjectName("user_comment_button")
        self.magnification_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.magnification_combobox.setGeometry(QtCore.QRect(10, 160, 51, 22))
        self.magnification_combobox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.magnification_combobox.setEditable(False)
        self.magnification_combobox.setCurrentText("")
        self.magnification_combobox.setObjectName("magnification_combobox")
        self.magnification_label = QtWidgets.QLabel(self.centralwidget)
        self.magnification_label.setGeometry(QtCore.QRect(10, 140, 111, 16))
        self.magnification_label.setObjectName("magnification_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 10, 1351, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.step_size_doublespin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.step_size_doublespin_box.setGeometry(QtCore.QRect(10, 260, 71, 22))
        self.step_size_doublespin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.step_size_doublespin_box.setDecimals(0)
        self.step_size_doublespin_box.setMinimum(5.0)
        self.step_size_doublespin_box.setMaximum(10000.0)
        self.step_size_doublespin_box.setSingleStep(5.0)
        self.step_size_doublespin_box.setProperty("value", 5.0)
        self.step_size_doublespin_box.setObjectName("step_size_doublespin_box")
        self.step_size_label = QtWidgets.QLabel(self.centralwidget)
        self.step_size_label.setGeometry(QtCore.QRect(10, 240, 131, 16))
        self.step_size_label.setObjectName("step_size_label")
        self.automation_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.automation_groupbox.setGeometry(QtCore.QRect(10, 290, 120, 241))
        self.automation_groupbox.setObjectName("automation_groupbox")
        self.cells_to_lyse_doublespin_box = QtWidgets.QDoubleSpinBox(self.automation_groupbox)
        self.cells_to_lyse_doublespin_box.setGeometry(QtCore.QRect(10, 40, 101, 22))
        self.cells_to_lyse_doublespin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cells_to_lyse_doublespin_box.setDecimals(0)
        self.cells_to_lyse_doublespin_box.setMinimum(1.0)
        self.cells_to_lyse_doublespin_box.setMaximum(10000.0)
        self.cells_to_lyse_doublespin_box.setSingleStep(1.0)
        self.cells_to_lyse_doublespin_box.setProperty("value", 1.0)
        self.cells_to_lyse_doublespin_box.setObjectName("cells_to_lyse_doublespin_box")
        self.cells_to_lyse_label = QtWidgets.QLabel(self.automation_groupbox)
        self.cells_to_lyse_label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.cells_to_lyse_label.setObjectName("cells_to_lyse_label")
        self.process_well_pushButton = QtWidgets.QPushButton(self.automation_groupbox)
        self.process_well_pushButton.setGeometry(QtCore.QRect(10, 200, 101, 31))
        self.process_well_pushButton.setObjectName("process_well_pushButton")
        self.lysis_mode_comboBox = QtWidgets.QComboBox(self.automation_groupbox)
        self.lysis_mode_comboBox.setGeometry(QtCore.QRect(10, 90, 101, 23))
        self.lysis_mode_comboBox.setObjectName("lysis_mode_comboBox")
        self.lysis_mode_label = QtWidgets.QLabel(self.automation_groupbox)
        self.lysis_mode_label.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.lysis_mode_label.setObjectName("lysis_mode_label")
        self.cell_type_to_lyse_comboBox = QtWidgets.QComboBox(self.automation_groupbox)
        self.cell_type_to_lyse_comboBox.setGeometry(QtCore.QRect(10, 170, 101, 23))
        self.cell_type_to_lyse_comboBox.setObjectName("cell_type_to_lyse_comboBox")
        self.cell_type_to_lyse_label = QtWidgets.QLabel(self.automation_groupbox)
        self.cell_type_to_lyse_label.setGeometry(QtCore.QRect(10, 120, 91, 41))
        self.cell_type_to_lyse_label.setObjectName("cell_type_to_lyse_label")
        self.record_push_button = QtWidgets.QPushButton(self.centralwidget)
        self.record_push_button.setGeometry(QtCore.QRect(20, 590, 101, 31))
        self.record_push_button.setCheckable(True)
        self.record_push_button.setObjectName("record_push_button")
        self.Tile_and_navigate_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Tile_and_navigate_pushbutton.setGeometry(QtCore.QRect(20, 540, 101, 41))
        self.Tile_and_navigate_pushbutton.setObjectName("Tile_and_navigate_pushbutton")
        self.cube_position_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.cube_position_combobox.setGeometry(QtCore.QRect(10, 210, 51, 22))
        self.cube_position_combobox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cube_position_combobox.setEditable(False)
        self.cube_position_combobox.setCurrentText("")
        self.cube_position_combobox.setObjectName("cube_position_combobox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 190, 121, 16))
        self.label.setObjectName("label")
        self.autofocus_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.autofocus_checkbox.setGeometry(QtCore.QRect(90, 210, 51, 21))
        self.autofocus_checkbox.setObjectName("autofocus_checkbox")
        self.exposure_doublespin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.exposure_doublespin_box.setGeometry(QtCore.QRect(20, 650, 101, 22))
        self.exposure_doublespin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.exposure_doublespin_box.setDecimals(0)
        self.exposure_doublespin_box.setMinimum(1.0)
        self.exposure_doublespin_box.setMaximum(1000000.0)
        self.exposure_doublespin_box.setSingleStep(1000.0)
        self.exposure_doublespin_box.setProperty("value", 5000.0)
        self.exposure_doublespin_box.setObjectName("exposure_doublespin_box")
        self.exposure_label = QtWidgets.QLabel(self.centralwidget)
        self.exposure_label.setGeometry(QtCore.QRect(20, 630, 131, 16))
        self.exposure_label.setObjectName("exposure_label")
        self.brightness_label = QtWidgets.QLabel(self.centralwidget)
        self.brightness_label.setGeometry(QtCore.QRect(20, 680, 131, 16))
        self.brightness_label.setObjectName("brightness_label")
        self.brightness_doublespin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.brightness_doublespin_box.setGeometry(QtCore.QRect(20, 700, 101, 22))
        self.brightness_doublespin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.brightness_doublespin_box.setDecimals(0)
        self.brightness_doublespin_box.setMinimum(1.0)
        self.brightness_doublespin_box.setMaximum(100.0)
        self.brightness_doublespin_box.setSingleStep(10.0)
        self.brightness_doublespin_box.setProperty("value", 50.0)
        self.brightness_doublespin_box.setObjectName("brightness_doublespin_box")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LCL System"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.misc_screenshot_button.setText(_translate("MainWindow", "Screenshot"))
        self.comment_box_label.setText(_translate("MainWindow", "Comment box"))
        self.user_comment_button.setText(_translate("MainWindow", "Add comment"))
        self.magnification_label.setText(_translate("MainWindow", "Magnification"))
        self.step_size_label.setText(_translate("MainWindow", "Stage Step Size"))
        self.automation_groupbox.setTitle(_translate("MainWindow", "Automation"))
        self.cells_to_lyse_label.setText(_translate("MainWindow", "Cells to Lyse"))
        self.process_well_pushButton.setText(_translate("MainWindow", "Process Well"))
        self.lysis_mode_label.setText(_translate("MainWindow", "Lysis Mode"))
        self.cell_type_to_lyse_label.setText(_translate("MainWindow", "Cell Type \n"
"to Lyse"))
        self.record_push_button.setText(_translate("MainWindow", "Record"))
        self.Tile_and_navigate_pushbutton.setText(_translate("MainWindow", "Tile and\n"
"Navigate"))
        self.label.setText(_translate("MainWindow", "Cube Position"))
        self.autofocus_checkbox.setText(_translate("MainWindow", "AF"))
        self.exposure_label.setText(_translate("MainWindow", "Exposure"))
        self.brightness_label.setText(_translate("MainWindow", "Brightness"))

