# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LCL.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1640, 727)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(-90, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.misc_screenshot_button = QtWidgets.QPushButton(self.centralwidget)
        self.misc_screenshot_button.setGeometry(QtCore.QRect(10, 10, 131, 21))
        self.misc_screenshot_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.misc_screenshot_button.setObjectName("misc_screenshot_button")
        self.comment_box = QtWidgets.QTextEdit(self.centralwidget)
        self.comment_box.setGeometry(QtCore.QRect(10, 53, 131, 41))
        self.comment_box.setObjectName("comment_box")
        self.comment_box_label = QtWidgets.QLabel(self.centralwidget)
        self.comment_box_label.setGeometry(QtCore.QRect(10, 35, 121, 16))
        self.comment_box_label.setObjectName("comment_box_label")
        self.user_comment_button = QtWidgets.QPushButton(self.centralwidget)
        self.user_comment_button.setGeometry(QtCore.QRect(10, 93, 131, 23))
        self.user_comment_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.user_comment_button.setObjectName("user_comment_button")
        self.magnification_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.magnification_combobox.setGeometry(QtCore.QRect(87, 125, 51, 22))
        self.magnification_combobox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.magnification_combobox.setEditable(False)
        self.magnification_combobox.setCurrentText("")
        self.magnification_combobox.setObjectName("magnification_combobox")
        self.magnification_label = QtWidgets.QLabel(self.centralwidget)
        self.magnification_label.setGeometry(QtCore.QRect(10, 120, 81, 31))
        self.magnification_label.setObjectName("magnification_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 10, 1351, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.step_size_doublespin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.step_size_doublespin_box.setGeometry(QtCore.QRect(10, 260, 71, 22))
        self.step_size_doublespin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.step_size_doublespin_box.setDecimals(0)
        self.step_size_doublespin_box.setMinimum(1.0)
        self.step_size_doublespin_box.setMaximum(10000.0)
        self.step_size_doublespin_box.setSingleStep(50.0)
        self.step_size_doublespin_box.setProperty("value", 50.0)
        self.step_size_doublespin_box.setObjectName("step_size_doublespin_box")
        self.step_size_label = QtWidgets.QLabel(self.centralwidget)
        self.step_size_label.setGeometry(QtCore.QRect(10, 240, 81, 16))
        self.step_size_label.setObjectName("step_size_label")
        self.automation_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.automation_groupbox.setGeometry(QtCore.QRect(150, 10, 120, 241))
        self.automation_groupbox.setObjectName("automation_groupbox")
        self.cells_to_lyse_doublespin_box = QtWidgets.QDoubleSpinBox(self.automation_groupbox)
        self.cells_to_lyse_doublespin_box.setGeometry(QtCore.QRect(10, 40, 101, 22))
        self.cells_to_lyse_doublespin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cells_to_lyse_doublespin_box.setDecimals(0)
        self.cells_to_lyse_doublespin_box.setMinimum(1.0)
        self.cells_to_lyse_doublespin_box.setMaximum(10000.0)
        self.cells_to_lyse_doublespin_box.setSingleStep(1.0)
        self.cells_to_lyse_doublespin_box.setProperty("value", 1.0)
        self.cells_to_lyse_doublespin_box.setObjectName("cells_to_lyse_doublespin_box")
        self.cells_to_lyse_label = QtWidgets.QLabel(self.automation_groupbox)
        self.cells_to_lyse_label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.cells_to_lyse_label.setObjectName("cells_to_lyse_label")
        self.process_well_pushButton = QtWidgets.QPushButton(self.automation_groupbox)
        self.process_well_pushButton.setGeometry(QtCore.QRect(10, 200, 101, 31))
        self.process_well_pushButton.setObjectName("process_well_pushButton")
        self.lysis_mode_comboBox = QtWidgets.QComboBox(self.automation_groupbox)
        self.lysis_mode_comboBox.setGeometry(QtCore.QRect(10, 90, 101, 23))
        self.lysis_mode_comboBox.setObjectName("lysis_mode_comboBox")
        self.lysis_mode_label = QtWidgets.QLabel(self.automation_groupbox)
        self.lysis_mode_label.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.lysis_mode_label.setObjectName("lysis_mode_label")
        self.cell_type_to_lyse_comboBox = QtWidgets.QComboBox(self.automation_groupbox)
        self.cell_type_to_lyse_comboBox.setGeometry(QtCore.QRect(10, 170, 101, 23))
        self.cell_type_to_lyse_comboBox.setObjectName("cell_type_to_lyse_comboBox")
        self.cell_type_to_lyse_label = QtWidgets.QLabel(self.automation_groupbox)
        self.cell_type_to_lyse_label.setGeometry(QtCore.QRect(10, 120, 91, 41))
        self.cell_type_to_lyse_label.setObjectName("cell_type_to_lyse_label")
        self.record_push_button = QtWidgets.QPushButton(self.centralwidget)
        self.record_push_button.setGeometry(QtCore.QRect(150, 310, 121, 31))
        self.record_push_button.setCheckable(True)
        self.record_push_button.setObjectName("record_push_button")
        self.tile_and_navigate_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.tile_and_navigate_pushbutton.setGeometry(QtCore.QRect(150, 260, 121, 41))
        self.tile_and_navigate_pushbutton.setObjectName("tile_and_navigate_pushbutton")
        self.exposure_doublespin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.exposure_doublespin_box.setGeometry(QtCore.QRect(150, 370, 101, 22))
        self.exposure_doublespin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.exposure_doublespin_box.setDecimals(0)
        self.exposure_doublespin_box.setMinimum(1.0)
        self.exposure_doublespin_box.setMaximum(10000.0)
        self.exposure_doublespin_box.setSingleStep(5.0)
        self.exposure_doublespin_box.setProperty("value", 5.0)
        self.exposure_doublespin_box.setObjectName("exposure_doublespin_box")
        self.exposure_label = QtWidgets.QLabel(self.centralwidget)
        self.exposure_label.setGeometry(QtCore.QRect(150, 350, 131, 16))
        self.exposure_label.setObjectName("exposure_label")
        self.brightness_label = QtWidgets.QLabel(self.centralwidget)
        self.brightness_label.setGeometry(QtCore.QRect(150, 400, 131, 16))
        self.brightness_label.setObjectName("brightness_label")
        self.brightness_doublespin_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.brightness_doublespin_box.setGeometry(QtCore.QRect(150, 420, 101, 22))
        self.brightness_doublespin_box.setFocusPolicy(QtCore.Qt.NoFocus)
        self.brightness_doublespin_box.setDecimals(0)
        self.brightness_doublespin_box.setMinimum(0.0)
        self.brightness_doublespin_box.setMaximum(100.0)
        self.brightness_doublespin_box.setSingleStep(10.0)
        self.brightness_doublespin_box.setProperty("value", 50.0)
        self.brightness_doublespin_box.setObjectName("brightness_doublespin_box")
        self.fluorescence_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.fluorescence_groupBox.setGeometry(QtCore.QRect(10, 290, 120, 171))
        self.fluorescence_groupBox.setObjectName("fluorescence_groupBox")
        self.excitation_lamp_on_label = QtWidgets.QLabel(self.fluorescence_groupBox)
        self.excitation_lamp_on_label.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.excitation_lamp_on_label.setObjectName("excitation_lamp_on_label")
        self.cube_position_combobox = QtWidgets.QComboBox(self.fluorescence_groupBox)
        self.cube_position_combobox.setGeometry(QtCore.QRect(10, 40, 51, 22))
        self.cube_position_combobox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cube_position_combobox.setEditable(False)
        self.cube_position_combobox.setCurrentText("")
        self.cube_position_combobox.setObjectName("cube_position_combobox")
        self.cube_position_label = QtWidgets.QLabel(self.fluorescence_groupBox)
        self.cube_position_label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.cube_position_label.setObjectName("cube_position_label")
        self.excitation_lamp_on_combobox = QtWidgets.QComboBox(self.fluorescence_groupBox)
        self.excitation_lamp_on_combobox.setGeometry(QtCore.QRect(10, 90, 71, 22))
        self.excitation_lamp_on_combobox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.excitation_lamp_on_combobox.setEditable(False)
        self.excitation_lamp_on_combobox.setCurrentText("")
        self.excitation_lamp_on_combobox.setObjectName("excitation_lamp_on_combobox")
        self.intensity_label = QtWidgets.QLabel(self.fluorescence_groupBox)
        self.intensity_label.setGeometry(QtCore.QRect(10, 120, 101, 16))
        self.intensity_label.setObjectName("intensity_label")
        self.intensity_doublespin_box = QtWidgets.QDoubleSpinBox(self.fluorescence_groupBox)
        self.intensity_doublespin_box.setGeometry(QtCore.QRect(10, 140, 71, 22))
        self.intensity_doublespin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.intensity_doublespin_box.setDecimals(0)
        self.intensity_doublespin_box.setMinimum(5.0)
        self.intensity_doublespin_box.setMaximum(100.0)
        self.intensity_doublespin_box.setSingleStep(10.0)
        self.intensity_doublespin_box.setProperty("value", 50.0)
        self.intensity_doublespin_box.setObjectName("intensity_doublespin_box")
        self.autofocus_groubox = QtWidgets.QGroupBox(self.centralwidget)
        self.autofocus_groubox.setGeometry(QtCore.QRect(10, 160, 120, 80))
        self.autofocus_groubox.setObjectName("autofocus_groubox")
        self.calibrate_af_pushbutton = QtWidgets.QPushButton(self.autofocus_groubox)
        self.calibrate_af_pushbutton.setGeometry(QtCore.QRect(10, 24, 80, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.calibrate_af_pushbutton.setFont(font)
        self.calibrate_af_pushbutton.setObjectName("calibrate_af_pushbutton")
        self.autofocus_checkbox = QtWidgets.QCheckBox(self.autofocus_groubox)
        self.autofocus_checkbox.setGeometry(QtCore.QRect(10, 55, 81, 21))
        self.autofocus_checkbox.setObjectName("autofocus_checkbox")
        self.laser_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.laser_groupbox.setGeometry(QtCore.QRect(10, 470, 120, 121))
        self.laser_groupbox.setObjectName("laser_groupbox")
        self.burst_count_double_spin_box = QtWidgets.QDoubleSpinBox(self.laser_groupbox)
        self.burst_count_double_spin_box.setGeometry(QtCore.QRect(10, 40, 66, 24))
        self.burst_count_double_spin_box.setDecimals(0)
        self.burst_count_double_spin_box.setMaximum(10000000.0)
        self.burst_count_double_spin_box.setSingleStep(1.0)
        self.burst_count_double_spin_box.setProperty("value", 50.0)
        self.burst_count_double_spin_box.setObjectName("burst_count_double_spin_box")
        self.repetition_rate_double_spin_box = QtWidgets.QDoubleSpinBox(self.laser_groupbox)
        self.repetition_rate_double_spin_box.setGeometry(QtCore.QRect(10, 90, 66, 24))
        self.repetition_rate_double_spin_box.setDecimals(0)
        self.repetition_rate_double_spin_box.setMinimum(1.0)
        self.repetition_rate_double_spin_box.setMaximum(1100.0)
        self.repetition_rate_double_spin_box.setSingleStep(10.0)
        self.repetition_rate_double_spin_box.setProperty("value", 50.0)
        self.repetition_rate_double_spin_box.setObjectName("repetition_rate_double_spin_box")
        self.burst_count_label = QtWidgets.QLabel(self.laser_groupbox)
        self.burst_count_label.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.burst_count_label.setObjectName("burst_count_label")
        self.repetition_rate_label = QtWidgets.QLabel(self.laser_groupbox)
        self.repetition_rate_label.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.repetition_rate_label.setObjectName("repetition_rate_label")
        self.retract_objective_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.retract_objective_checkbox.setGeometry(QtCore.QRect(150, 450, 111, 21))
        self.retract_objective_checkbox.setObjectName("retract_objective_checkbox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LCL System"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.misc_screenshot_button.setText(_translate("MainWindow", "Screenshot"))
        self.comment_box_label.setText(_translate("MainWindow", "Comment box"))
        self.user_comment_button.setText(_translate("MainWindow", "Add comment"))
        self.magnification_label.setText(_translate("MainWindow", "Magnification"))
        self.step_size_doublespin_box.setSuffix(_translate("MainWindow", "μm"))
        self.step_size_label.setText(_translate("MainWindow", "Stage Step Size"))
        self.automation_groupbox.setTitle(_translate("MainWindow", "Automation"))
        self.cells_to_lyse_label.setText(_translate("MainWindow", "Cells to Lyse"))
        self.process_well_pushButton.setText(_translate("MainWindow", "Process Well"))
        self.lysis_mode_label.setText(_translate("MainWindow", "Lysis Mode"))
        self.cell_type_to_lyse_label.setText(_translate("MainWindow", "Cell Type \n"
"to Lyse"))
        self.record_push_button.setText(_translate("MainWindow", "Record"))
        self.tile_and_navigate_pushbutton.setText(_translate("MainWindow", "Tile and\n"
"Navigate"))
        self.exposure_doublespin_box.setSuffix(_translate("MainWindow", "ms"))
        self.exposure_label.setText(_translate("MainWindow", "Exposure"))
        self.brightness_label.setText(_translate("MainWindow", "Brightness"))
        self.brightness_doublespin_box.setSuffix(_translate("MainWindow", "%"))
        self.fluorescence_groupBox.setTitle(_translate("MainWindow", "Fluorescence"))
        self.excitation_lamp_on_label.setText(_translate("MainWindow", "Excitation"))
        self.cube_position_label.setText(_translate("MainWindow", "Cube Position"))
        self.intensity_label.setText(_translate("MainWindow", "Intensity"))
        self.intensity_doublespin_box.setSuffix(_translate("MainWindow", "%"))
        self.autofocus_groubox.setTitle(_translate("MainWindow", "Autofocus"))
        self.calibrate_af_pushbutton.setText(_translate("MainWindow", "Calibrate"))
        self.autofocus_checkbox.setText(_translate("MainWindow", "Lock Focus"))
        self.laser_groupbox.setTitle(_translate("MainWindow", "Laser"))
        self.repetition_rate_double_spin_box.setSuffix(_translate("MainWindow", "hz"))
        self.burst_count_label.setText(_translate("MainWindow", "Burst Count"))
        self.repetition_rate_label.setText(_translate("MainWindow", "Repetition Rate"))
        self.retract_objective_checkbox.setText(_translate("MainWindow", "Retract Objective"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

