# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/mdryden/src/LCL_software/ui/LCL.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1646, 1035)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.ForceTabbedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.acquisition_dockwidget = QtWidgets.QDockWidget(MainWindow)
        self.acquisition_dockwidget.setMinimumSize(QtCore.QSize(271, 1015))
        self.acquisition_dockwidget.setFloating(False)
        self.acquisition_dockwidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.acquisition_dockwidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.acquisition_dockwidget.setObjectName("acquisition_dockwidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.acquisition_groupbox = QtWidgets.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acquisition_groupbox.sizePolicy().hasHeightForWidth())
        self.acquisition_groupbox.setSizePolicy(sizePolicy)
        self.acquisition_groupbox.setMinimumSize(QtCore.QSize(0, 479))
        self.acquisition_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.acquisition_groupbox.setFlat(False)
        self.acquisition_groupbox.setCheckable(False)
        self.acquisition_groupbox.setObjectName("acquisition_groupbox")
        self.gridLayout = QtWidgets.QGridLayout(self.acquisition_groupbox)
        self.gridLayout.setObjectName("gridLayout")
        self.intensity_label = QtWidgets.QLabel(self.acquisition_groupbox)
        self.intensity_label.setObjectName("intensity_label")
        self.gridLayout.addWidget(self.intensity_label, 5, 0, 1, 1)
        self.cube_position_label = QtWidgets.QLabel(self.acquisition_groupbox)
        self.cube_position_label.setObjectName("cube_position_label")
        self.gridLayout.addWidget(self.cube_position_label, 3, 0, 1, 2)
        self.cube_position_combobox = QtWidgets.QComboBox(self.acquisition_groupbox)
        self.cube_position_combobox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cube_position_combobox.setEditable(False)
        self.cube_position_combobox.setCurrentText("")
        self.cube_position_combobox.setObjectName("cube_position_combobox")
        self.gridLayout.addWidget(self.cube_position_combobox, 4, 0, 1, 3)
        self.brightness_label = QtWidgets.QLabel(self.acquisition_groupbox)
        self.brightness_label.setObjectName("brightness_label")
        self.gridLayout.addWidget(self.brightness_label, 1, 0, 1, 1)
        self.exposure_label = QtWidgets.QLabel(self.acquisition_groupbox)
        self.exposure_label.setObjectName("exposure_label")
        self.gridLayout.addWidget(self.exposure_label, 0, 0, 1, 1)
        self.gain_label = QtWidgets.QLabel(self.acquisition_groupbox)
        self.gain_label.setObjectName("gain_label")
        self.gridLayout.addWidget(self.gain_label, 2, 0, 1, 1)
        self.preset_comboBox = QtWidgets.QComboBox(self.acquisition_groupbox)
        self.preset_comboBox.setObjectName("preset_comboBox")
        self.gridLayout.addWidget(self.preset_comboBox, 10, 0, 1, 3)
        self.excitation_lamp_on_combobox = QtWidgets.QComboBox(self.acquisition_groupbox)
        self.excitation_lamp_on_combobox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.excitation_lamp_on_combobox.setEditable(False)
        self.excitation_lamp_on_combobox.setCurrentText("")
        self.excitation_lamp_on_combobox.setObjectName("excitation_lamp_on_combobox")
        self.gridLayout.addWidget(self.excitation_lamp_on_combobox, 7, 0, 1, 3)
        self.acquisition_preset_label = QtWidgets.QLabel(self.acquisition_groupbox)
        self.acquisition_preset_label.setObjectName("acquisition_preset_label")
        self.gridLayout.addWidget(self.acquisition_preset_label, 9, 0, 1, 1)
        self.emission_label = QtWidgets.QLabel(self.acquisition_groupbox)
        self.emission_label.setObjectName("emission_label")
        self.gridLayout.addWidget(self.emission_label, 8, 0, 1, 1)
        self.excitation_lamp_on_label = QtWidgets.QLabel(self.acquisition_groupbox)
        self.excitation_lamp_on_label.setObjectName("excitation_lamp_on_label")
        self.gridLayout.addWidget(self.excitation_lamp_on_label, 6, 0, 1, 1)
        self.save_preset_pushButton = QtWidgets.QPushButton(self.acquisition_groupbox)
        self.save_preset_pushButton.setObjectName("save_preset_pushButton")
        self.gridLayout.addWidget(self.save_preset_pushButton, 11, 0, 1, 3)
        self.remove_preset_pushButton = QtWidgets.QPushButton(self.acquisition_groupbox)
        self.remove_preset_pushButton.setObjectName("remove_preset_pushButton")
        self.gridLayout.addWidget(self.remove_preset_pushButton, 13, 0, 1, 3)
        self.add_preset_pushButton = QtWidgets.QPushButton(self.acquisition_groupbox)
        self.add_preset_pushButton.setObjectName("add_preset_pushButton")
        self.gridLayout.addWidget(self.add_preset_pushButton, 12, 0, 1, 3)
        self.exposure_spin_box = QtWidgets.QSpinBox(self.acquisition_groupbox)
        self.exposure_spin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.exposure_spin_box.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.exposure_spin_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.exposure_spin_box.setMinimum(1)
        self.exposure_spin_box.setMaximum(5000)
        self.exposure_spin_box.setDisplayIntegerBase(10)
        self.exposure_spin_box.setObjectName("exposure_spin_box")
        self.gridLayout.addWidget(self.exposure_spin_box, 0, 2, 1, 1)
        self.brightness_spin_box = QtWidgets.QSpinBox(self.acquisition_groupbox)
        self.brightness_spin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.brightness_spin_box.setSuffix(" %")
        self.brightness_spin_box.setMaximum(100)
        self.brightness_spin_box.setSingleStep(10)
        self.brightness_spin_box.setObjectName("brightness_spin_box")
        self.gridLayout.addWidget(self.brightness_spin_box, 1, 2, 1, 1)
        self.gain_spin_box = QtWidgets.QSpinBox(self.acquisition_groupbox)
        self.gain_spin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gain_spin_box.setMaximum(480)
        self.gain_spin_box.setSingleStep(10)
        self.gain_spin_box.setObjectName("gain_spin_box")
        self.gridLayout.addWidget(self.gain_spin_box, 2, 2, 1, 1)
        self.intensity_spin_box = QtWidgets.QSpinBox(self.acquisition_groupbox)
        self.intensity_spin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.intensity_spin_box.setMaximum(100)
        self.intensity_spin_box.setSingleStep(10)
        self.intensity_spin_box.setObjectName("intensity_spin_box")
        self.gridLayout.addWidget(self.intensity_spin_box, 5, 2, 1, 1)
        self.emission_spin_box = QtWidgets.QSpinBox(self.acquisition_groupbox)
        self.emission_spin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.emission_spin_box.setMinimum(0)
        self.emission_spin_box.setMaximum(850)
        self.emission_spin_box.setSingleStep(10)
        self.emission_spin_box.setProperty("value", 0)
        self.emission_spin_box.setObjectName("emission_spin_box")
        self.gridLayout.addWidget(self.emission_spin_box, 8, 2, 1, 1)
        self.verticalLayout.addWidget(self.acquisition_groupbox)
        self.imaging_groupbox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.imaging_groupbox.setObjectName("imaging_groupbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.imaging_groupbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tile_preset_label = QtWidgets.QLabel(self.imaging_groupbox)
        self.tile_preset_label.setObjectName("tile_preset_label")
        self.gridLayout_2.addWidget(self.tile_preset_label, 3, 0, 1, 2)
        self.tile_preset_listView = QtWidgets.QListView(self.imaging_groupbox)
        self.tile_preset_listView.setObjectName("tile_preset_listView")
        self.gridLayout_2.addWidget(self.tile_preset_listView, 4, 0, 1, 4)
        self.tile_cols_label = QtWidgets.QLabel(self.imaging_groupbox)
        self.tile_cols_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tile_cols_label.setObjectName("tile_cols_label")
        self.gridLayout_2.addWidget(self.tile_cols_label, 5, 0, 1, 1)
        self.tile_cols_spinBox = QtWidgets.QSpinBox(self.imaging_groupbox)
        self.tile_cols_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.tile_cols_spinBox.setMinimum(1)
        self.tile_cols_spinBox.setObjectName("tile_cols_spinBox")
        self.gridLayout_2.addWidget(self.tile_cols_spinBox, 5, 1, 1, 1)
        self.tile_rows_spinBox = QtWidgets.QSpinBox(self.imaging_groupbox)
        self.tile_rows_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.tile_rows_spinBox.setMinimum(1)
        self.tile_rows_spinBox.setObjectName("tile_rows_spinBox")
        self.gridLayout_2.addWidget(self.tile_rows_spinBox, 5, 2, 1, 1)
        self.tile_rows_label = QtWidgets.QLabel(self.imaging_groupbox)
        self.tile_rows_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tile_rows_label.setObjectName("tile_rows_label")
        self.gridLayout_2.addWidget(self.tile_rows_label, 5, 3, 1, 1)
        self.misc_screenshot_button = QtWidgets.QPushButton(self.imaging_groupbox)
        self.misc_screenshot_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.misc_screenshot_button.setObjectName("misc_screenshot_button")
        self.gridLayout_2.addWidget(self.misc_screenshot_button, 1, 0, 1, 4)
        self.record_push_button = QtWidgets.QPushButton(self.imaging_groupbox)
        self.record_push_button.setCheckable(True)
        self.record_push_button.setObjectName("record_push_button")
        self.gridLayout_2.addWidget(self.record_push_button, 2, 0, 1, 4)
        self.tile_and_navigate_pushbutton = QtWidgets.QPushButton(self.imaging_groupbox)
        self.tile_and_navigate_pushbutton.setObjectName("tile_and_navigate_pushbutton")
        self.gridLayout_2.addWidget(self.tile_and_navigate_pushbutton, 6, 0, 1, 4)
        self.imagelabel_lineEdit = QtWidgets.QLineEdit(self.imaging_groupbox)
        self.imagelabel_lineEdit.setAcceptDrops(False)
        self.imagelabel_lineEdit.setMaxLength(255)
        self.imagelabel_lineEdit.setPlaceholderText("")
        self.imagelabel_lineEdit.setClearButtonEnabled(False)
        self.imagelabel_lineEdit.setObjectName("imagelabel_lineEdit")
        self.gridLayout_2.addWidget(self.imagelabel_lineEdit, 0, 2, 1, 2)
        self.imagelabel_label = QtWidgets.QLabel(self.imaging_groupbox)
        self.imagelabel_label.setObjectName("imagelabel_label")
        self.gridLayout_2.addWidget(self.imagelabel_label, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.imaging_groupbox)
        self.comment_groupbox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.comment_groupbox.setObjectName("comment_groupbox")
        self.comment_layout = QtWidgets.QVBoxLayout(self.comment_groupbox)
        self.comment_layout.setObjectName("comment_layout")
        self.comment_box = QtWidgets.QPlainTextEdit(self.comment_groupbox)
        self.comment_box.setBackgroundVisible(False)
        self.comment_box.setObjectName("comment_box")
        self.comment_layout.addWidget(self.comment_box)
        self.user_comment_button = QtWidgets.QPushButton(self.comment_groupbox)
        self.user_comment_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.user_comment_button.setObjectName("user_comment_button")
        self.comment_layout.addWidget(self.user_comment_button)
        self.verticalLayout.addWidget(self.comment_groupbox)
        self.acquisition_dockwidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.acquisition_dockwidget)
        self.instrument_dockwidget = QtWidgets.QDockWidget(MainWindow)
        self.instrument_dockwidget.setMinimumSize(QtCore.QSize(250, 123))
        self.instrument_dockwidget.setFloating(False)
        self.instrument_dockwidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.instrument_dockwidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.instrument_dockwidget.setObjectName("instrument_dockwidget")
        self.dockWidgetContents1 = QtWidgets.QWidget()
        self.dockWidgetContents1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents1.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents1.setSizePolicy(sizePolicy)
        self.dockWidgetContents1.setAutoFillBackground(False)
        self.dockWidgetContents1.setObjectName("dockWidgetContents1")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.dockWidgetContents1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents1)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 226, 989))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout1 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout1.setObjectName("gridLayout1")
        self.stage_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage_groupbox.sizePolicy().hasHeightForWidth())
        self.stage_groupbox.setSizePolicy(sizePolicy)
        self.stage_groupbox.setObjectName("stage_groupbox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.stage_groupbox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.step_size_label = QtWidgets.QLabel(self.stage_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_size_label.sizePolicy().hasHeightForWidth())
        self.step_size_label.setSizePolicy(sizePolicy)
        self.step_size_label.setMinimumSize(QtCore.QSize(0, 16))
        self.step_size_label.setObjectName("step_size_label")
        self.verticalLayout_11.addWidget(self.step_size_label)
        self.step_size_spin_box = QtWidgets.QSpinBox(self.stage_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_size_spin_box.sizePolicy().hasHeightForWidth())
        self.step_size_spin_box.setSizePolicy(sizePolicy)
        self.step_size_spin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.step_size_spin_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.step_size_spin_box.setMaximum(500)
        self.step_size_spin_box.setObjectName("step_size_spin_box")
        self.verticalLayout_11.addWidget(self.step_size_spin_box)
        self.gridLayout1.addWidget(self.stage_groupbox, 1, 0, 1, 1)
        self.autofocus_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autofocus_groupbox.sizePolicy().hasHeightForWidth())
        self.autofocus_groupbox.setSizePolicy(sizePolicy)
        self.autofocus_groupbox.setMinimumSize(QtCore.QSize(0, 96))
        self.autofocus_groupbox.setObjectName("autofocus_groupbox")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.autofocus_groupbox)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.autofocus_status_label = QtWidgets.QLabel(self.autofocus_groupbox)
        self.autofocus_status_label.setText("")
        self.autofocus_status_label.setObjectName("autofocus_status_label")
        self.verticalLayout1.addWidget(self.autofocus_status_label)
        self.af_logcal_button = QtWidgets.QPushButton(self.autofocus_groupbox)
        self.af_logcal_button.setObjectName("af_logcal_button")
        self.verticalLayout1.addWidget(self.af_logcal_button)
        self.af_idle_button = QtWidgets.QPushButton(self.autofocus_groupbox)
        self.af_idle_button.setObjectName("af_idle_button")
        self.verticalLayout1.addWidget(self.af_idle_button)
        self.af_ready_button = QtWidgets.QPushButton(self.autofocus_groupbox)
        self.af_ready_button.setObjectName("af_ready_button")
        self.verticalLayout1.addWidget(self.af_ready_button)
        self.af_lock_button = QtWidgets.QPushButton(self.autofocus_groupbox)
        self.af_lock_button.setObjectName("af_lock_button")
        self.verticalLayout1.addWidget(self.af_lock_button)
        self.af_gaincal_button = QtWidgets.QPushButton(self.autofocus_groupbox)
        self.af_gaincal_button.setObjectName("af_gaincal_button")
        self.verticalLayout1.addWidget(self.af_gaincal_button)
        self.af_dither_button = QtWidgets.QPushButton(self.autofocus_groupbox)
        self.af_dither_button.setObjectName("af_dither_button")
        self.verticalLayout1.addWidget(self.af_dither_button)
        self.gridLayout1.addWidget(self.autofocus_groupbox, 2, 0, 1, 1)
        self.laser_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.laser_groupbox.sizePolicy().hasHeightForWidth())
        self.laser_groupbox.setSizePolicy(sizePolicy)
        self.laser_groupbox.setMinimumSize(QtCore.QSize(125, 213))
        self.laser_groupbox.setObjectName("laser_groupbox")
        self.verticalLayout2 = QtWidgets.QVBoxLayout(self.laser_groupbox)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.burst_count_label = QtWidgets.QLabel(self.laser_groupbox)
        self.burst_count_label.setObjectName("burst_count_label")
        self.verticalLayout2.addWidget(self.burst_count_label)
        self.burst_count_double_spin_box = QtWidgets.QDoubleSpinBox(self.laser_groupbox)
        self.burst_count_double_spin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.burst_count_double_spin_box.setDecimals(0)
        self.burst_count_double_spin_box.setMaximum(10000000.0)
        self.burst_count_double_spin_box.setSingleStep(1.0)
        self.burst_count_double_spin_box.setProperty("value", 1.0)
        self.burst_count_double_spin_box.setObjectName("burst_count_double_spin_box")
        self.verticalLayout2.addWidget(self.burst_count_double_spin_box)
        self.repetition_rate_label = QtWidgets.QLabel(self.laser_groupbox)
        self.repetition_rate_label.setObjectName("repetition_rate_label")
        self.verticalLayout2.addWidget(self.repetition_rate_label)
        self.repetition_rate_double_spin_box = QtWidgets.QDoubleSpinBox(self.laser_groupbox)
        self.repetition_rate_double_spin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.repetition_rate_double_spin_box.setDecimals(0)
        self.repetition_rate_double_spin_box.setMinimum(1.0)
        self.repetition_rate_double_spin_box.setMaximum(1000.0)
        self.repetition_rate_double_spin_box.setSingleStep(100.0)
        self.repetition_rate_double_spin_box.setProperty("value", 1000.0)
        self.repetition_rate_double_spin_box.setObjectName("repetition_rate_double_spin_box")
        self.verticalLayout2.addWidget(self.repetition_rate_double_spin_box)
        self.z_offset_label = QtWidgets.QLabel(self.laser_groupbox)
        self.z_offset_label.setObjectName("z_offset_label")
        self.verticalLayout2.addWidget(self.z_offset_label)
        self.z_offset_spinBox = QtWidgets.QSpinBox(self.laser_groupbox)
        self.z_offset_spinBox.setMinimum(-1000)
        self.z_offset_spinBox.setMaximum(1000)
        self.z_offset_spinBox.setObjectName("z_offset_spinBox")
        self.verticalLayout2.addWidget(self.z_offset_spinBox)
        self.laser_image_checkbox = QtWidgets.QCheckBox(self.laser_groupbox)
        self.laser_image_checkbox.setChecked(True)
        self.laser_image_checkbox.setObjectName("laser_image_checkbox")
        self.verticalLayout2.addWidget(self.laser_image_checkbox)
        self.laser_video_checkbox = QtWidgets.QCheckBox(self.laser_groupbox)
        self.laser_video_checkbox.setChecked(True)
        self.laser_video_checkbox.setObjectName("laser_video_checkbox")
        self.verticalLayout2.addWidget(self.laser_video_checkbox)
        self.gridLayout1.addWidget(self.laser_groupbox, 3, 0, 1, 1)
        self.objective_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objective_groupbox.sizePolicy().hasHeightForWidth())
        self.objective_groupbox.setSizePolicy(sizePolicy)
        self.objective_groupbox.setMinimumSize(QtCore.QSize(138, 116))
        self.objective_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.objective_groupbox.setObjectName("objective_groupbox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.objective_groupbox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.magnification_label = QtWidgets.QLabel(self.objective_groupbox)
        self.magnification_label.setObjectName("magnification_label")
        self.verticalLayout_10.addWidget(self.magnification_label)
        self.magnification_combobox = QtWidgets.QComboBox(self.objective_groupbox)
        self.magnification_combobox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.magnification_combobox.setEditable(False)
        self.magnification_combobox.setCurrentText("")
        self.magnification_combobox.setObjectName("magnification_combobox")
        self.verticalLayout_10.addWidget(self.magnification_combobox)
        self.retract_objective_checkbox = QtWidgets.QCheckBox(self.objective_groupbox)
        self.retract_objective_checkbox.setObjectName("retract_objective_checkbox")
        self.verticalLayout_10.addWidget(self.retract_objective_checkbox)
        self.gridLayout1.addWidget(self.objective_groupbox, 0, 0, 1, 1)
        self.automation_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.automation_groupbox.sizePolicy().hasHeightForWidth())
        self.automation_groupbox.setSizePolicy(sizePolicy)
        self.automation_groupbox.setMinimumSize(QtCore.QSize(139, 255))
        self.automation_groupbox.setObjectName("automation_groupbox")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.automation_groupbox)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.cells_to_lyse_label = QtWidgets.QLabel(self.automation_groupbox)
        self.cells_to_lyse_label.setObjectName("cells_to_lyse_label")
        self.verticalLayout_12.addWidget(self.cells_to_lyse_label)
        self.cells_to_lyse_doublespin_box = QtWidgets.QDoubleSpinBox(self.automation_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cells_to_lyse_doublespin_box.sizePolicy().hasHeightForWidth())
        self.cells_to_lyse_doublespin_box.setSizePolicy(sizePolicy)
        self.cells_to_lyse_doublespin_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cells_to_lyse_doublespin_box.setDecimals(0)
        self.cells_to_lyse_doublespin_box.setMinimum(1.0)
        self.cells_to_lyse_doublespin_box.setMaximum(10000.0)
        self.cells_to_lyse_doublespin_box.setSingleStep(1.0)
        self.cells_to_lyse_doublespin_box.setProperty("value", 1.0)
        self.cells_to_lyse_doublespin_box.setObjectName("cells_to_lyse_doublespin_box")
        self.verticalLayout_12.addWidget(self.cells_to_lyse_doublespin_box)
        self.lysis_mode_label = QtWidgets.QLabel(self.automation_groupbox)
        self.lysis_mode_label.setObjectName("lysis_mode_label")
        self.verticalLayout_12.addWidget(self.lysis_mode_label)
        self.lysis_mode_comboBox = QtWidgets.QComboBox(self.automation_groupbox)
        self.lysis_mode_comboBox.setObjectName("lysis_mode_comboBox")
        self.verticalLayout_12.addWidget(self.lysis_mode_comboBox)
        self.cell_type_to_lyse_label = QtWidgets.QLabel(self.automation_groupbox)
        self.cell_type_to_lyse_label.setObjectName("cell_type_to_lyse_label")
        self.verticalLayout_12.addWidget(self.cell_type_to_lyse_label)
        self.cell_type_to_lyse_comboBox = QtWidgets.QComboBox(self.automation_groupbox)
        self.cell_type_to_lyse_comboBox.setObjectName("cell_type_to_lyse_comboBox")
        self.verticalLayout_12.addWidget(self.cell_type_to_lyse_comboBox)
        self.process_well_pushButton = QtWidgets.QPushButton(self.automation_groupbox)
        self.process_well_pushButton.setObjectName("process_well_pushButton")
        self.verticalLayout_12.addWidget(self.process_well_pushButton)
        self.gridLayout1.addWidget(self.automation_groupbox, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout1.addItem(spacerItem, 5, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_13.addWidget(self.scrollArea)
        self.instrument_dockwidget.setWidget(self.dockWidgetContents1)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.instrument_dockwidget)

        self.retranslateUi(MainWindow)
        MainWindow.destroyed.connect(self.acquisition_dockwidget.close)
        MainWindow.destroyed.connect(self.instrument_dockwidget.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LCL System"))
        self.acquisition_dockwidget.setWindowTitle(_translate("MainWindow", "Acquisition"))
        self.acquisition_groupbox.setTitle(_translate("MainWindow", "Imaging Settings"))
        self.intensity_label.setText(_translate("MainWindow", "Intensity"))
        self.cube_position_label.setText(_translate("MainWindow", "Cube Position"))
        self.brightness_label.setText(_translate("MainWindow", "Brightness"))
        self.exposure_label.setText(_translate("MainWindow", "Exposure"))
        self.gain_label.setText(_translate("MainWindow", "Gain"))
        self.acquisition_preset_label.setText(_translate("MainWindow", "Preset"))
        self.emission_label.setText(_translate("MainWindow", "Emission"))
        self.excitation_lamp_on_label.setText(_translate("MainWindow", "Excitation"))
        self.save_preset_pushButton.setText(_translate("MainWindow", "Save/Overwrite"))
        self.remove_preset_pushButton.setText(_translate("MainWindow", "Remove Preset"))
        self.add_preset_pushButton.setText(_translate("MainWindow", "Add Preset"))
        self.exposure_spin_box.setSuffix(_translate("MainWindow", " ms"))
        self.intensity_spin_box.setSuffix(_translate("MainWindow", " %"))
        self.emission_spin_box.setSuffix(_translate("MainWindow", " nm"))
        self.imaging_groupbox.setTitle(_translate("MainWindow", "Imaging"))
        self.tile_preset_label.setText(_translate("MainWindow", "Presets to Use For\n"
"Tiling:"))
        self.tile_cols_label.setText(_translate("MainWindow", "Columns"))
        self.tile_rows_label.setText(_translate("MainWindow", "Rows"))
        self.misc_screenshot_button.setText(_translate("MainWindow", "Screenshot"))
        self.record_push_button.setText(_translate("MainWindow", "Record"))
        self.tile_and_navigate_pushbutton.setText(_translate("MainWindow", "Tile"))
        self.imagelabel_label.setText(_translate("MainWindow", "Image Label"))
        self.comment_groupbox.setTitle(_translate("MainWindow", "Comments"))
        self.user_comment_button.setText(_translate("MainWindow", "Add comment"))
        self.instrument_dockwidget.setWindowTitle(_translate("MainWindow", "Instrument"))
        self.stage_groupbox.setTitle(_translate("MainWindow", "Stage"))
        self.step_size_label.setText(_translate("MainWindow", "Stage Step Size"))
        self.step_size_spin_box.setSuffix(_translate("MainWindow", " µm"))
        self.autofocus_groupbox.setTitle(_translate("MainWindow", "Autofocus"))
        self.af_logcal_button.setText(_translate("MainWindow", "Log Cal"))
        self.af_idle_button.setText(_translate("MainWindow", "Idle"))
        self.af_ready_button.setText(_translate("MainWindow", "Ready"))
        self.af_lock_button.setText(_translate("MainWindow", "Lock"))
        self.af_gaincal_button.setText(_translate("MainWindow", "Gain Cal"))
        self.af_dither_button.setText(_translate("MainWindow", "Dither"))
        self.laser_groupbox.setTitle(_translate("MainWindow", "Laser"))
        self.burst_count_label.setText(_translate("MainWindow", "Burst Count"))
        self.repetition_rate_label.setText(_translate("MainWindow", "Repetition Rate"))
        self.repetition_rate_double_spin_box.setSuffix(_translate("MainWindow", " hz"))
        self.z_offset_label.setText(_translate("MainWindow", "Z offset (0.1 µm)"))
        self.laser_image_checkbox.setText(_translate("MainWindow", "Record images"))
        self.laser_video_checkbox.setText(_translate("MainWindow", "Record video"))
        self.objective_groupbox.setTitle(_translate("MainWindow", "Objective"))
        self.magnification_label.setText(_translate("MainWindow", "Magnification"))
        self.retract_objective_checkbox.setText(_translate("MainWindow", "Retract Objective"))
        self.automation_groupbox.setTitle(_translate("MainWindow", "Automation"))
        self.cells_to_lyse_label.setText(_translate("MainWindow", "Cells to Lyse"))
        self.lysis_mode_label.setText(_translate("MainWindow", "Lysis Mode"))
        self.cell_type_to_lyse_label.setText(_translate("MainWindow", "Cell Type \n"
"to Lyse"))
        self.process_well_pushButton.setText(_translate("MainWindow", "Process Well"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

